Party_members=['丁海龙','孙俊','方姚','雷亦男', '张印华']
print('原参加晚会名单'+str(Party_members))
Invitation_message=[]
Invitation_message.append('Dear '+Party_members[0]+' ,请来参加我的晚会\t')
Invitation_message.append('Dear '+Party_members[1]+' ,请来参加我的晚会\t')
Invitation_message.append('Dear '+Party_members[2]+' ,请来参加我的晚会\t')
Invitation_message.append('Dear '+Party_members[3]+' ,请来参加我的晚会\t')
Invitation_message.append('Dear '+Party_members[4]+' ,请来参加我的晚会\t')
print(Invitation_message[0])
print(Invitation_message[1])
print(Invitation_message[2])
print(Invitation_message[3])
print(Invitation_message[4])
unattend_name=Party_members.pop(3)
print(unattend_name+'不能来参加晚会')
print('新的参加名单'+str(Party_members))
print('因为找到了新的更大的餐桌，所以新加一部分成员')
Party_members.insert(0,'杨波')
Party_members.insert(3,'赵斌')
Party_members.append('吴小祥')
print(Party_members)
print('因为不可抗因素，只能邀请两位嘉宾')
del_members0=Party_members.pop(0)
print(str(del_members0)+'先生，很抱歉你不能来参加晚会')
del_members1=Party_members.pop(0)
print(str(del_members1)+'先生，很抱歉你不能来参加晚会')
del_members2=Party_members.pop(0)
print(str(del_members2)+'先生，很抱歉你不能来参加晚会')
del_members3=Party_members.pop(0)
print(str(del_members3)+'先生，很抱歉你不能来参加晚会')
del_members4=Party_members.pop(0)
print(str(del_members4)+'先生，很抱歉你不能来参加晚会')
Invitation_message.append('Dear '+Party_members[0]+' ,请来参加我的晚会\t')
Invitation_message.append('Dear '+Party_members[1]+' ,请来参加我的晚会\t')
print(Invitation_message[0])
print(Invitation_message[1])
del Party_members[1]
del Party_members[0]
print('因为没有晚会，所以没有人可以参加')
print('新的名单是'+str(Party_members))
