cars1 = ['shanxi','shannxi','neimenggu','beijing','hangzhou']
cars2= ['shanxi','shannxi','neimenggu','beijing','hangzhou']
print(cars1)
cars1.sort()
print(cars1)
print(cars2)
print(sorted(cars2))
print(cars2)
cars1.sort(reverse=True)
print(cars1)
cars1.reverse()
print(cars1)
cars1.reverse()
print(cars1)
print(len(cars1))
